### ISSUE TITLE
非*注解*配置的Reference代理服务，spring-boot的placeholder无法正常解析

### ISSUE THREAD

**Issue by CrisLi** [apache/dubbo-spring-boot-project#537] opened 2019-07-02 05:29 UTC
dubbo version: 2.7.2
dubbo-spring-boot version: 2.7.1
spring-boot version 2.1.6.Release

启动类如下
```java

@EnableDubbo
@SpringBootApplication
@ImportResource("classpath:dubbo-config.xml")
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}

```

Spring Boot配置文件

```yml
spring:
  application:
    name: first-dubbo-app-consumer
server:
  port: 8085

dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1:2181}
    session: 10000
  consumer:
    check: false
  metadata-report:
    address: zookeeper://${zookeeper.address:127.0.0.1:2181}
  config-center:
    address: zookeeper://${zookeeper.address:127.0.0.1:2181}

management:
  endpoints:
    web:
      exposure:
        include: "*"

```

Dubbo XML配置文件

```xml
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
    xmlns="http://www.springframework.org/schema/beans"
    xmlns:p="http://www.springframework.org/schema/p"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans.xsd
        http://dubbo.apache.org/schema/dubbo
        http://dubbo.apache.org/schema/dubbo/dubbo.xsd">

    <dubbo:reference id="helloService" interface="org.chris.demo.dubbo.api.HelloService" generic="true" />

</beans>
```

因为一些原因，希望使用xml文件配置一些服务，但引入xml配置后，配置中心的地址被错误的解析了。报错信息如下。
```
Caused by: java.lang.NumberFormatException: For input string: "2181}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_201]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_201]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_201]
	at org.apache.dubbo.common.URL.valueOf(URL.java:269) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.common.utils.UrlUtils.parseURL(UrlUtils.java:100) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.ConfigCenterConfig.toUrl(ConfigCenterConfig.java:102) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.AbstractInterfaceConfig.prepareEnvironment(AbstractInterfaceConfig.java:289) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.AbstractInterfaceConfig.startConfigCenter(AbstractInterfaceConfig.java:279) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.ReferenceConfig.checkAndUpdateSubConfigs(ReferenceConfig.java:220) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:244) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.init(ReferenceAnnotationBeanPostProcessor.java:173) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.access$100(ReferenceAnnotationBeanPostProcessor.java:146) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildInvocationHandler(ReferenceAnnotationBeanPostProcessor.java:140) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildProxy(ReferenceAnnotationBeanPostProcessor.java:123) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:119) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:52) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.getInjectedObject(AnnotationInjectedBeanPostProcessor.java:337) ~[dubbo-2.7.2.jar:2.7.2]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor$AnnotatedFieldElement.inject(AnnotationInjectedBeanPostProcessor.java:517) ~[dubbo-2.7.2.jar:2.7.2]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.postProcessPropertyValues(AnnotationInjectedBeanPostProcessor.java:130) ~[dubbo-2.7.2.jar:2.7.2]
	... 17 common frames omitted
```

如果将xml配置去掉，dubbo就能够正确解析spring-boot配置文件中的内容。是不是xml文件加载的配置信息早于spring-boot环境启动，造成spring-boot的环境配置没有完全加载完。

**Comment by CrisLi** [comment] 2019-07-02 08:13
经测试发现，不光是xml配置服务存在此问题，使用Java API形式配置也存在同样问题。单如果只用注解的形式配置Reference，spring-boot配置文件中的placeholder是可以被正常替换的。

例如配置了一个
```java
    @Bean("helloService")
    public ReferenceConfig<GenericService> helloService() {
        ReferenceConfig<GenericService> reference = new ReferenceConfig<GenericService>();
        reference.setInterface(HelloService.class.getName());
        reference.setGeneric(true);
        return reference;
    }
```
```java
ReferenceConfig<GenericService> reference = (ReferenceConfig<GenericService>) context.getBean("helloService");

GenericService service = reference.get();
```

**Comment by tswstarplanet** [comment] 2019-08-09 07:02
I have reproduced the problem, it's because the BeanPostProcessor that process the dubbo configuration yml file is not loaded

**Comment by tswstarplanet** [comment] 2019-08-09 13:48
I have create a related issue in the core dubbo repository
https://github.com/apache/dubbo/issues/4783

**Comment by tswstarplanet** [comment] 2019-08-09 17:15
@CrisLi I have submit a pr to fix it. You can pull it as a branch and test it.

**Comment by CrisLi** [comment] 2019-09-05 13:19
do we have plan when  this pull request will be merged? release with version 2.7.4?

**Comment by mercyblitz** [comment] 2019-09-09 06:25
Please PR first

**Comment by huadong** [comment] 2019-09-12 03:28
`org.apache.dubbo.spring.boot.beans.factory.config.DubboConfigBeanDefinitionConflictProcessor.resolveUniqueApplicationConfigBean(BeanDefinitionRegistry, ConfigurableListableBeanFactory)`

invoked before

`org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(ConfigurableListableBeanFactory)`

while `org.apache.dubbo.spring.boot.beans.factory.config.DubboConfigBeanDefinitionConflictProcessor.resolveUniqueApplicationConfigBean(BeanDefinitionRegistry, ConfigurableListableBeanFactory)`

invoke 

`org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(ListableBeanFactory, Class<?>)`

it will cause beans get instanced before placeholder values are resolved.

**Comment by huadong** [comment] 2019-09-12 04:02
@mercyblitz  
why `org.apache.dubbo.spring.boot.beans.factory.config.DubboConfigBeanDefinitionConflictProcessor` implements `org.springframework.beans.factory.support.BeanDefinitionRegistryPostProcessor`
and does not implement `org.springframework.beans.factory.config.BeanFactoryPostProcessor`?

implements `org.springframework.beans.factory.support.BeanDefinitionRegistryPostProcessor` will be invoked before `org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(ConfigurableListableBeanFactory)`。

**Closed** 2019-10-30 06:39 UTC
